### ISSUE TITLE
FreeRTOS support for Pico and micro-Ros?

### ISSUE THREAD

**Issue by jondurrant** [micro-ROS/micro_ros_raspberrypi_pico_sdk#777]
## Issue template

- Hardware description: RPI Pico
- RTOS: FreeRTOS
- Installation type: micro_ros_raspberrypi_pico_sdk
- Version or commit hash: n/a

#### Steps to reproduce the issue
Are there plans to support FreeRTOS on the pico? How much of the binary library would work on FreeRTOS as is?

It would be useful to have more visibility of the sourcecode of the library to help us assess what we could do with he library.

**Comment by pablogs9** [comment]
You have the whole source code available in the ROS 2 + micro-ROS repos that uses this library. In this case, they are precompiled due to build system limitations. But in general, all the micro-ROS code is open source.

Regarding FreeRTOS + pico, it is out of the scope of this repo. We support micro-ROS in the Raspberry Pi Pico SDK, if this SDK support FreeRTOS you will be able to run all of them together.
